apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomee
  labels:
     app: tomcat
     type: front-end
spec:
  template:
     metadata:
       name: tomcat-pod
       labels:
         app: tomcatapp
         type: front-end
     spec:
         imagePullSecrets:
         - name: pullsecret
         containers:
           - name: tomcat-container
             image: "omprakashsurwase/tomcatomimage"
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcatapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 30001
      port: 80
      nodePort: 30001
